### ISSUE TITLE
EORROR：inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by mufeng-74** [ucbrise/waldo#5]
Hello, when I run scripts/runExperiment.py, I receive the following error, and the corresponding part of the source code is placed below. How can I solve this problem?
Thank you very much for your answer！

user@user-Redmi-G:~/library/waldo$ python3 scripts/runExperiment.py
Traceback (most recent call last):
  File "scripts/runExperiment.py", line 12, in <module>
    from ssh_util import *
  File "/home/user/library/waldo/scripts/ssh_util.py", line 189
    cmd = "killall " + process
                             ^
TabError: inconsistent use of tabs and spaces in indentation

![image](https://user-images.githubusercontent.com/76865606/198694304-fb280504-c481-4e96-b663-4fd0afee5b33.png)

**Comment by mufeng-74** [comment]
sorry, now i solved him, thanks a lot
